name: Release

on:
  push:
    tags:
      - "v*" 

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build all platforms
        run: bun run build:all

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/dgate-linux
            dist/dgate-macos
            dist/dgate-macos-arm64
            dist/dgate-windows.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
